AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to Create an EC2 instance"

Parameters:
  InstanceName:
    Type: String
    Description: "EC2 machine Name"
    Default: ""
  InstanceType:
    Type: String
    Description: "EC2 instance type"
    Default: ""
  KeyName:
    Type: String
    Description: "Key pair name for EC2 instance"
    Default: ""

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-008677ef1baf82eaf"
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  InstanceId:
    Description: "ID of the newly created EC2 instance"
    Value: !Ref MyEC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"
